IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "At the POKéMON LEAGUE, you will\n"
    .string "face the ELITE FOUR all in a row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it!\n"
    .string "Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_YouCantGoIn::
    .string "You can't go in without\n"
    .string "any POKéMON.$"

IndigoPlateau_PokemonCenter_1F_Text_WelcomeToTheEliteFour::
    .string "Welcome to the ELITE FOUR! Would\n"
    .string "you like to take on the challenge?$"

IndigoPlateau_PokemonCenter_1F_Text_SpeakWithTheClerk::
    .string "Please speak with the clerk if you\n"
    .string "have any questions.$"

IndigoPlateau_PokemonCenter_1F_Text_ThereYouGo::
    .string "There you go. Check your POKéMON\n"
    .string "and BAG. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_SwitchOutTeam::
    .string "Welcome back! Would you like to\n"
    .string "switch out your POKéMON?$"

IndigoPlateau_PokemonCenter_1F_Text_YouShouldTry::
    .string "You should attempt the challenge\n"
    .string "at least once with that team\p"
    .string "before switching it out.\n"
    .string "Sometimes your POKéMON will\p"
    .string "surprise you with their power!$"

IndigoPlateau_PokemonCenter_1F_Text_WouldYouLikeMeToExplain::
    .string "Hello {PLAYER}! My name is ANISH.\n"
    .string "I created this ROM Hack.\p"
    .string "Would you like me to explain the\n"
    .string "premise of this challenge?$"

IndigoPlateau_PokemonCenter_1F_Text_RulesExplain::
    .string "In the POKéMON ELITE FOUR challenge,\n"
    .string "you are provided with six randomly\l"
    .string "generated POKéMON that are\l"
    .string "obtainable in a normal playthrough\l"
    .string "of this game up to the point of\l"
    .string "the POKéMON LEAGUE.\p"
    .string "Don't worry though, you'll\n"
    .string "get a varied enough team in\l"
    .string "terms of both stats and types.\p"
    .string "Your POKéMON will also hopefully\n"
    .string "have some good moves. If not,\l"
    .string "make the most out of what you got.\p"
    .string "You'll also get a BAG full of\n"
    .string "useful items and TMs, but no revives,\l"
    .string "so try your best to not let\l"
    .string "any of your POKéMON faint.\p"
    .string "You can attempt the challenge as\n"
    .string "many times as you wish with the\l"
    .string "same team or switch it out\l"
    .string "as long as you've made one\l"
    .string "attempt. Although, your BAG will\l"
    .string "randomly reset every time.\p"
    .string "Oh, well I've been chirping on for\n"
    .string "much too long now. Talk to the\l"
    .string "COOLTRAINER up front to get your\l"
    .string "team and items. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_Enjoy::
    .string "No worries. Enjoy the challenge\n"
    .string "and may the odds be in your favor!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "LORELEI of the ELITE FOUR is\n"
    .string "absent, you see.\p"
    .string "As a result, the POKéMON LEAGUE is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHA's GHOST-type POKéMON are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type POKéMON\n"
    .string "and raised them to the max.\p"
    .string "I went at AGATHA feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get\n"
    .string "that scary lady hollering.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Maybe becoming an ELITE FOUR\n"
    .string "member is in the blood.\p"
    .string "From what I've heard, LANCE has\n"
    .string "a cousin who's a GYM LEADER\l"
    .string "somewhere far away.$"
