IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "At the POKéMON LEAGUE, you will\n"
    .string "face the ELITE FOUR all in a row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it!\n"
    .string "Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_WelcomeToTheEliteFour::
    .string "Welcome to the ELITE FOUR! Would\n"
    .string "you like to take on the challenge?$"

IndigoPlateau_PokemonCenter_1F_Text_SpeakWithTheClerk::
    .string "Please speak with the clerk if you\n"
    .string "have any questions.$"

IndigoPlateau_PokemonCenter_1F_Text_ThereYouGo::
    .string "There you go. Check your\n"
    .string "POKéMON. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_SwitchOutTeam::
    .string "Welcome back! Would you like\n"
    .string "to switch out your POKéMON?$"

IndigoPlateau_PokemonCenter_1F_Text_YouShouldTry::
    .string "You should attempt the challenge\n"
    .string "at least once with that team\p"
    .string "before switching it out.\n"
    .string "Sometimes your POKéMON will\p"
    .string "surprise you with their power!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "LORELEI of the ELITE FOUR is\n"
    .string "absent, you see.\p"
    .string "As a result, the POKéMON LEAGUE is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHA's GHOST-type POKéMON are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type POKéMON\n"
    .string "and raised them to the max.\p"
    .string "I went at AGATHA feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get\n"
    .string "that scary lady hollering.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Maybe becoming an ELITE FOUR\n"
    .string "member is in the blood.\p"
    .string "From what I've heard, LANCE has\n"
    .string "a cousin who's a GYM LEADER\l"
    .string "somewhere far away.$"
